(()=>{if(window.__PIXELSQUAD__)return;window.__PIXELSQUAD__=true;
const KEY="pixelsquad_state";let stored={};try{const value=JSON.parse(localStorage.getItem(KEY)||"{}");if(value&&typeof value==="object"&&!Array.isArray(value))stored=value}catch{}
let panelDragCleanup=null;
const S={tab:["effects","commands"].includes(stored.tab)?"home":stored.tab||"home",enables:Array.isArray(window.PixelSquadDefaultEnables)?window.PixelSquadDefaultEnables:[],handitems:Array.isArray(window.PixelSquadDefaultHanditems)?window.PixelSquadDefaultHanditems:[],itemFavorites:Array.isArray(stored.itemFavorites)?stored.itemFavorites:[],height:Number(stored.height)||0,direction:Number(stored.direction)||0,favorites:Array.isArray(stored.favorites)?stored.favorites:[],history:Array.isArray(stored.history)?stored.history:[],lastAction:"",custom:{accent:stored.custom?.accent||"#00dcbf",background:stored.custom?.background||"#111725",panel:stored.custom?.panel||"#151d2e",text:stored.custom?.text||"#edf2ff",opacity:Number(stored.custom?.opacity)||96,radius:Number(stored.custom?.radius??14),scale:Number(stored.custom?.scale)||100,compact:!!stored.custom?.compact,sidebar:stored.custom?.sidebar!==false}};
function itemCollection(defaults,items){const rows=new Map((defaults||[]).map(x=>[String(x.id),x]));for(const x of Array.isArray(items)?items:[]){if(!x||!(typeof x.id==="number"||typeof x.id==="string"&&/^\d+$/.test(x.id))||!Number.isSafeInteger(Number(x.id))||Number(x.id)<0)continue;const key=String(Number(x.id)),current=rows.get(key);rows.set(key,current?{...x,...current}:{id:Number(x.id),name:String(x.name||"Item"),image:typeof x.image==="string"&&/^https:\/\//.test(x.image)?x.image:""})}return [...rows.values()]}
function enablesList(items){return itemCollection(window.PixelSquadDefaultEnables,items)}
function handitemsList(items){return itemCollection(window.PixelSquadDefaultHanditems,items)}
const wired=[["Ativadores","Entrada no quarto","Gatilho quando alguém entra"],["Ativadores","Periodicamente","Executa em intervalo"],["Efeitos","Super Wired","Executa configurações do Super Wired"],["Efeitos","Mudar estado","Altera o estado de mobis selecionados"],["Efeitos","Teleporte aleatório","Espalha mobis em outro mobi"],["Condições","Badge","Verifica emblema"],["Condições","Direitos","Verifica direitos"],["Condições","VIP","Verifica VIP"],["Condições","Grupo","Verifica grupo"],["Condições","Nome","Compara nome"],["Seletores","Mobis","Seleciona mobis"],["Seletores","Usuários","Seleciona usuários"]];
const commands=["enable","fastwalk","handitem","pullmode","pushmode","diagonal","kickpower","sit","lay","lock","roommute","walkthrough","clickthrough","addpoint","removepoint","setpoint","moonwalk","player:stand","tag","removetag","showgroupforum","randomstate","randomteleport","badge","nobadge","hasrights","norights","hasvip","novip","gender","groupmember","nogroupmember","nohanditem","mission","nomission","username","copiar","bfloor","up","spin","state","wired","autofloor","tile","pyramid","eject","playtest","abracar","push","pull","kis","soco","quickpoll","ativar","desativar","setmax","tele","aus","afk","random","habbletname","setspeed","blockroom","floor","bcfloor","pickall","pickwired"];
const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function persist(){localStorage.setItem(KEY,JSON.stringify({tab:S.tab,height:S.height,direction:S.direction,favorites:S.favorites,history:S.history,itemFavorites:S.itemFavorites,custom:S.custom}))}

function appearanceSettings(main){
  const section=document.createElement("section");
  section.className="panel-position-settings";
  section.innerHTML='<h3>Aparência do painel</h3><p class="muted">Personalize a PixelSquad dentro do jogo. As alterações são aplicadas e salvas automaticamente.</p><div class="ps-custom-grid"></div>';
  const grid=section.querySelector(".ps-custom-grid");
  const add=(key,title,type,min,max,step)=>{
    const label=document.createElement("label");
    const text=document.createElement("span");
    text.textContent=title;
    const input=document.createElement("input");
    input.type=type;input.dataset.appearance=key;
    if(type==="checkbox"){input.checked=S.custom[key];label.className="ps-toggle"}
    else input.value=String(S.custom[key]);
    if(type==="range"){input.min=String(min);input.max=String(max);input.step=String(step)}
    label.append(text,input);
    const output=document.createElement("output");
    if(type==="range"){output.textContent=input.value+(key==="radius"?" px":"%");label.append(output)}
    input.addEventListener("input",()=>{
      S.custom[key]=type==="checkbox"?input.checked:type==="range"?Number(input.value):input.value;
      if(type==="range")output.textContent=input.value+(key==="radius"?" px":"%");
      applyCustom();persist();
    });
    grid.appendChild(label);
  };
  add("accent","Cor de destaque","color");
  add("background","Cor do fundo","color");
  add("panel","Cor dos cartões","color");
  add("text","Cor dos textos","color");
  add("opacity","Opacidade","range",30,100,1);
  add("radius","Cantos arredondados","range",0,30,1);
  add("scale","Tamanho do texto","range",80,140,5);
  add("compact","Modo compacto","checkbox");
  add("sidebar","Menu lateral","checkbox");
  const reset=document.createElement("button");
  reset.type="button";reset.textContent="Restaurar aparência padrão";
  reset.addEventListener("click",()=>{
    S.custom={accent:"#00dcbf",background:"#111725",panel:"#151d2e",text:"#edf2ff",opacity:96,radius:14,scale:100,compact:false,sidebar:true};
    applyCustom();persist();render();toast("Aparência padrão restaurada");
  });
  section.appendChild(reset);
  main.querySelector(".panel-position-settings").before(section);
}

function applyCustom(){const root=document.querySelector("#pixelsquad");if(!root)return;const q=S.custom;root.style.setProperty("--ps-accent",q.accent);root.style.setProperty("--ps-bg",q.background);root.style.setProperty("--ps-panel",q.panel);root.style.setProperty("--ps-text",q.text);root.style.setProperty("--ps-opacity",(q.opacity/100).toFixed(2));root.style.setProperty("--ps-radius",q.radius+"px");root.style.setProperty("--ps-scale",(q.scale/100).toFixed(2));root.classList.toggle("ps-compact",q.compact);root.classList.toggle("ps-sidebar",q.sidebar)}
function toast(msg){let t=document.getElementById("pixelsquad-toast");if(!t){t=document.createElement("div");t.id="pixelsquad-toast";document.body.appendChild(t)}t.textContent=msg;t.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove("show"),1900)}
function action(name,data={}){S.lastAction=name;S.history.push({action:name,data,time:Date.now()});S.history=S.history.slice(-50);persist();toast("PixelSquad • "+name)}
function bridge(command){const v=String(command||"").trim();if(!v)return false;window.postMessage({source:"pixelsquad",type:"PS_COMMAND",requestId:"ps_"+Date.now()+"_"+Math.random().toString(36).slice(2),command:v},"*");action("command",{command:v});return true}
const cmd=(n,p="")=>bridge(":"+n+(String(p).trim()?" "+String(p).trim():""));
function openBuilder(){const re=/constru|construction|builder|build|furni|mobis/i;const els=[...document.querySelectorAll("button,[role=button],a")].filter(e=>{const r=e.getBoundingClientRect(),t=(e.innerText||e.textContent||"")+" "+(e.getAttribute("aria-label")||"")+" "+(e.getAttribute("title")||"");return r.width>0&&r.height>0&&re.test(t)});const hit=els.find(e=>/constru|construction|builder/i.test((e.innerText||"")+" "+(e.getAttribute("aria-label")||"")));if(hit){hit.click();action("native-builder");return true}toast("Abra o quarto e clique no construtor nativo do Habblet.");return false}
function nativeTool(name){const re={undo:/desfazer|undo/i,redo:/refazer|redo/i,select:/selecion|select/i,move:/mover|move/i,rotate:/girar|rotate/i,freeze:/congelar|freeze/i,unfreeze:/descongelar|unfreeze/i}[name];if(!re)return false;const hit=[...document.querySelectorAll("button,[role=button],a")].find(e=>{const r=e.getBoundingClientRect(),t=(e.innerText||e.textContent||"")+" "+(e.getAttribute("aria-label")||"")+" "+(e.getAttribute("title")||"");return r.width>0&&r.height>0&&re.test(t)});if(hit){hit.click();action(name);return true}toast("Abra o construtor nativo para usar "+name+".");return false}
function inspect(){window.postMessage({source:"pixelsquad",type:"PS_DISCOVER",requestId:"ps_"+Date.now()},"*");toast("Inspecionando o cliente...")}
function syncLauncher(){const button=document.getElementById("pixelsquad-launch");if(!button)return;const opened=!!document.getElementById("pixelsquad");button.hidden=window.PixelSquadGame?.active!==true;button.setAttribute("aria-expanded",String(opened));button.setAttribute("aria-label",opened?"Fechar PixelSquad":"Abrir PixelSquad")}
function closePanel(){panelDragCleanup?.();panelDragCleanup=null;document.getElementById("pixelsquad")?.remove();syncLauncher()}
function togglePanel(){if(document.getElementById("pixelsquad"))closePanel();else panel()}
function panel(){if(window.PixelSquadGame?.refresh()!==true)return;closePanel();const root=document.createElement("div");root.id="pixelsquad";root.innerHTML='<div class="box"><header class="drag"><div><strong><img src="'+chrome.runtime.getURL("icons/icon128.png")+'"> PIXELSQUAD</strong><small>Construção • Wired • Visuais • Tradução</small></div><button id="ps-close">×</button></header><nav id="ps-nav"></nav><main id="ps-main"></main><footer class="ps-panel-footer"><button id="ps-creator" type="button" aria-label="Abrir perfil de Pricilao.">Feito por Pricilao.</button><span>Abra com :pixel</span></footer></div>';document.body.appendChild(root);
const tabs=[["home","⌂"],["avatar","👤"],["build","▦"],["visuals","👕"],["room","🏠"],["enables","✋"],["wired","⚙"],["chat","💬"],["translate","🌐"],["tools","🧰"],["antiflood","🛡"],["settings","☷"]],nav=root.querySelector("#ps-nav");nav.innerHTML='<div class="ps-nav-brand">PixelSquad</div>'+tabs.map(([k,i])=>'<button data-tab="'+k+'" class="'+((S.tab==="handitems"?"enables":S.tab)===k?"active":"")+'"><span class="ps-nav-icon" aria-hidden="true">'+i+'</span><span class="ps-nav-label">'+esc(typeof psT==="function"?psT(k):k)+'</span></button>').join("");nav.onclick=e=>{const b=e.target.closest("[data-tab]");if(b){S.tab=b.dataset.tab;persist();render()}};root.querySelector("#ps-close").onclick=closePanel;root.querySelector("#ps-creator").onclick=()=>{const requestId="creator_"+Date.now()+"_"+Math.random().toString(36).slice(2);const direct=new CustomEvent("pixelsquad-open-creator",{detail:{requestId},cancelable:true});if(document.dispatchEvent(direct)){const message={source:"pixelsquad",type:"PS_OPEN_CREATOR",requestId};window.postMessage(message,"*");for(const frame of document.querySelectorAll("iframe")){try{frame.contentWindow?.postMessage(message,"*")}catch{}}}toast("Abrindo perfil de Pricilao. …")};drag(root);applyCustom();render();resizePanel(root);syncLauncher()}
function drag(root){const box=root.querySelector(".box"),h=root.querySelector(".drag"),POSKEY="pixelsquad_panel_position";let on=false,ox=0,oy=0;let saved=null;try{saved=JSON.parse(localStorage.getItem(POSKEY)||"null")}catch{};const applyPosition=pos=>{if(!pos||!Number.isFinite(Number(pos.x))||!Number.isFinite(Number(pos.y)))return;box.classList.add("ps-custom-position");box.style.setProperty("--ps-left",Math.round(pos.x)+"px");box.style.setProperty("--ps-top",Math.round(pos.y)+"px")};if(saved)applyPosition(saved);const clamp=()=>{if(!box.classList.contains("ps-custom-position"))return;const r=box.getBoundingClientRect();const x=Math.max(8,Math.min(innerWidth-r.width-8,r.left));const y=Math.max(8,Math.min(innerHeight-r.height-8,r.top));applyPosition({x,y});localStorage.setItem(POSKEY,JSON.stringify({x:Math.round(x),y:Math.round(y)}))};h.onpointerdown=e=>{if(e.target.closest("button"))return;on=true;const r=box.getBoundingClientRect();ox=e.clientX-r.left;oy=e.clientY-r.top;box.classList.add("ps-custom-position");h.setPointerCapture?.(e.pointerId)};h.onpointermove=e=>{if(!on)return;const x=Math.max(8,Math.min(innerWidth-box.offsetWidth-8,e.clientX-ox));const y=Math.max(8,Math.min(innerHeight-box.offsetHeight-8,e.clientY-oy));box.style.setProperty("--ps-left",Math.round(x)+"px");box.style.setProperty("--ps-top",Math.round(y)+"px")};const finish=()=>{if(!on)return;on=false;const r=box.getBoundingClientRect();const x=Math.max(8,Math.min(innerWidth-r.width-8,r.left));const y=Math.max(8,Math.min(innerHeight-r.height-8,r.top));applyPosition({x,y});localStorage.setItem(POSKEY,JSON.stringify({x:Math.round(x),y:Math.round(y)}));toast("Posição do painel salva")};h.onpointerup=finish;h.onpointercancel=finish;window.addEventListener("resize",clamp);panelDragCleanup=()=>window.removeEventListener("resize",clamp);h.title="Arraste para mover o painel";h.ondblclick=()=>{box.classList.remove("ps-custom-position");box.style.removeProperty("--ps-left");box.style.removeProperty("--ps-top");localStorage.removeItem(POSKEY);toast("Posição restaurada")}}

function resizePanel(root){
 const box=root.querySelector(".box"),key="pixelsquad_panel_size",posKey="pixelsquad_panel_position";
 const grip=document.createElement("button");grip.type="button";grip.className="ps-resize-grip";grip.textContent="↘";
 grip.title="Arraste para aumentar ou diminuir. Use as setas para ajustar.";
 grip.setAttribute("aria-label","Redimensionar painel");box.appendChild(grip);
 let saved=null,drag=null;try{saved=JSON.parse(localStorage.getItem(key)||"null")}catch{}
 const size=()=>box.getBoundingClientRect();
 const save=()=>{const r=size();try{localStorage.setItem(key,JSON.stringify({width:Math.round(r.width),height:Math.round(r.height)}))}catch{}};
 const anchor=()=>{
  const r=size(),minW=Math.min(320,Math.max(24,innerWidth-24)),minH=Math.min(280,Math.max(24,innerHeight-24));
  const x=Math.max(8,Math.min(Math.max(8,innerWidth-minW-8),r.left)),y=Math.max(8,Math.min(Math.max(8,innerHeight-minH-8),r.top));
  box.classList.add("ps-custom-position");box.style.setProperty("--ps-left",Math.round(x)+"px");box.style.setProperty("--ps-top",Math.round(y)+"px");
  try{localStorage.setItem(posKey,JSON.stringify({x,y}))}catch{}
 };
 const apply=(width,height)=>{
  const r=size(),maxW=Math.max(24,innerWidth-r.left-8),maxH=Math.max(24,innerHeight-r.top-8);
  width=Math.round(Math.max(Math.min(320,maxW),Math.min(maxW,width)));
  height=Math.round(Math.max(Math.min(280,maxH),Math.min(maxH,height)));
  box.style.setProperty("--ps-user-width",width+"px");box.style.setProperty("--ps-user-height",height+"px");
  box.style.setProperty("width",width+"px","important");box.style.setProperty("height",height+"px","important");box.classList.add("ps-user-size");
 };
 if(Number.isFinite(saved?.width)&&Number.isFinite(saved?.height)){anchor();apply(saved.width,saved.height);}
 grip.onpointerdown=e=>{
  if(e.button!==0)return;e.preventDefault();anchor();const r=size();
  drag={id:e.pointerId,x:e.clientX,y:e.clientY,width:r.width,height:r.height};grip.setPointerCapture?.(e.pointerId);
 };
 grip.onpointermove=e=>{if(drag?.id===e.pointerId){e.preventDefault();apply(drag.width+e.clientX-drag.x,drag.height+e.clientY-drag.y)}};
 const finish=e=>{if(drag?.id!==e.pointerId)return;drag=null;save();if(grip.hasPointerCapture?.(e.pointerId))grip.releasePointerCapture(e.pointerId)};
 grip.onpointerup=finish;grip.onpointercancel=finish;
 grip.onlostpointercapture=()=>{if(drag){drag=null;save()}};
 grip.onkeydown=e=>{
  const deltas={ArrowRight:[1,0],ArrowLeft:[-1,0],ArrowDown:[0,1],ArrowUp:[0,-1]},delta=deltas[e.key];if(!delta)return;
  e.preventDefault();anchor();const r=size(),step=e.shiftKey?40:10;apply(r.width+delta[0]*step,r.height+delta[1]*step);save();
 };
 const onResize=()=>{anchor();const r=size();apply(r.width,r.height);save()};window.addEventListener("resize",onResize);
 const prior=panelDragCleanup;panelDragCleanup=()=>{prior?.();window.removeEventListener("resize",onResize)};
}

async function sendPanel(text){const v=String(text||"").trim();if(!v)return;const tr=window.PixelSquadTranslate,c=tr?.getConfig?.();if(c?.enabled&&c.outgoing&&!/^[:/]/.test(v)){try{const r=await tr.translate(v,c.target,c.source);tr.rememberOutgoing(r.text);bridge(r.text);return}catch{}}bridge(v)}
function render(){const m=document.querySelector("#pixelsquad #ps-main");if(!m)return;m.onclick=null;for(const b of document.querySelectorAll("#ps-nav [data-tab]")){const selected=b.dataset.tab===(S.tab==="handitems"?"enables":S.tab);b.classList.toggle("active",selected);b.setAttribute("aria-current",selected?"page":"false")}const title=document.querySelector("#pixelsquad header strong");if(title)title.textContent="PixelSquad • "+(typeof psT==="function"?psT(S.tab):S.tab);
if(S.tab==="home"){const shortcuts=[["room","🏠","Quarto","Floor e configurações do quarto"],["visuals","👕","Aparência","Crie e visualize novos visuais"],["wired","⚙","Wired","Ferramentas e configurações"],["settings","☷","Configurações","Cores, tamanho e posição"]];m.innerHTML='<input id="ps-home-search" placeholder="Buscar funcionalidade..." aria-label="Buscar funcionalidade"><p class="muted">Atalhos rápidos</p><div class="grid ps-home-shortcuts">'+shortcuts.map(([tab,icon,label,detail])=>'<button data-go="'+tab+'"><span class="ps-shortcut-icon">'+icon+'</span><b>'+label+'</b><small>'+detail+'</small></button>').join("")+'</div><div class="status">Abra a PixelSquad pelo comando <b>:pixel</b>. Arraste o ícone ou o cabeçalho para mover.</div>';m.querySelector("#ps-home-search").oninput=e=>{const q=e.target.value.toLocaleLowerCase("pt-BR");for(const button of m.querySelectorAll("[data-go]"))button.hidden=!button.textContent.toLocaleLowerCase("pt-BR").includes(q)};m.onclick=e=>{const button=e.target.closest("[data-go]");if(button){S.tab=button.dataset.go;persist();render();for(const nav of document.querySelectorAll("#ps-nav [data-tab]"))nav.classList.toggle("active",nav.dataset.tab===(S.tab==="handitems"?"enables":S.tab))}}}
if(S.tab==="avatar"){const a=[["sit","Sentar",0],["lay","Deitar",0],["moonwalk","Moonwalk",0],["copiar","Copiar visual",0],["random","Visual aleatório",0],["enable","Enable",1],["handitem","Handitem",1]];m.innerHTML='<h2>Personagem</h2><div class="avatar-grid">'+a.map(x=>'<button class="avatar-tool" data-avatar="'+esc(x[0])+'" data-param="'+x[2]+'">'+esc(x[1])+'</button>').join("")+'</div><input id="ps-avatar-param" placeholder="Parâmetro (ID, nome...)"><button id="ps-avatar-custom">Executar comando</button>';m.onclick=e=>{const b=e.target.closest("[data-avatar]");if(!b)return;if(b.dataset.avatar==="random"){window.PixelSquadAvatar?.open();return}const p=m.querySelector("#ps-avatar-param").value.trim();if(b.dataset.param==="1"&&!p){toast("Informe o parâmetro");return}cmd(b.dataset.avatar,p)};m.querySelector("#ps-avatar-custom").onclick=()=>{const p=m.querySelector("#ps-avatar-param").value.trim();if(p)bridge(p.startsWith(":")?p:":"+p)}}
if(S.tab==="build"){m.innerHTML='<h2>Construção / Decoração</h2><p class="muted">O Habblet disponibiliza um construtor nativo com ações de mobis, áreas e histórico. O PixelSquad concentra esse acesso e os comandos auxiliares.</p><div class="tools"><button data-b="native">Abrir construtor nativo</button><button data-b="inspect">Inspecionar cliente</button><button data-b="select">Selecionar mobi</button><button data-b="move">Mover</button><button data-b="rotate">Girar</button><button data-b="undo">Desfazer</button><button data-b="redo">Refazer</button><button data-b="freeze">Congelar</button><button data-b="unfreeze">Descongelar</button></div><hr><label>Altura<input id="ps-height" type="number" step="0.5" value="'+S.height+'"></label><label>Rotação<select id="ps-direction"><option>0</option><option>90</option><option>180</option><option>270</option></select></label><div class="tools"><button data-c="up">Aplicar :up</button><button data-c="spin">Aplicar :spin</button><button data-c="state">Aplicar :state</button><button data-c="tile">Abrir :tile</button></div><div class="status">Depois de abrir o construtor nativo, você poderá usar seleção por mobi/área, mover, copiar, recolher, alterar altura/estado e desfazer/refazer conforme os recursos disponíveis na conta/quarto.</div>';m.querySelector("#ps-direction").value=String(S.direction);m.querySelector("#ps-height").onchange=e=>{S.height=Number(e.target.value)||0;persist()};m.querySelector("#ps-direction").onchange=e=>{S.direction=Number(e.target.value)||0;persist()};m.onclick=e=>{const b=e.target.closest("[data-b]");if(b){if(b.dataset.b==="native")openBuilder();else if(b.dataset.b==="inspect")inspect();else nativeTool(b.dataset.b)}const c=e.target.closest("[data-c]");if(c){const v=c.dataset.c==="up"?S.height:c.dataset.c==="spin"?S.direction:prompt("Valor:","0");if(v!==null&&v!==undefined)cmd(c.dataset.c,String(v))}}}
if(S.tab==="visuals"){m.innerHTML='<h2>Visuais</h2><div class="tools"><button data-v="copiar">Copiar visual</button><button data-v="random">Visual aleatório</button><button data-v="editor">Abrir editor nativo</button></div><div class="status">A aplicação das peças do visual permanece no editor nativo do Habblet.</div>';m.onclick=e=>{const b=e.target.closest("[data-v]");if(!b)return;if(b.dataset.v==="copiar")cmd("copiar");else if(b.dataset.v==="random")window.PixelSquadAvatar?.open();else openBuilder()}}
if(S.tab==="room"){const r=[["bfloor","Floor Plan"],["floor","Editor chão/parede"],["home","Cafofo"],["roommute","Silenciar"],["lock","Trancar"],["wired","Ocultar Wired"],["autofloor","Limpar pisos vazios"],["pyramid","Pirâmides Wired"],["playtest","Modo teste"],["pickall","Recolher meus mobis"],["pickwired","Recolher Wireds"]];m.innerHTML='<h2>Quarto</h2><div class="tools">'+r.map(x=>'<button data-room="'+x[0]+'">'+esc(x[1])+'</button>').join("")+'</div>';m.onclick=e=>{const b=e.target.closest("[data-room]");if(b)cmd(b.dataset.room)}}
if(S.tab==="enables"||S.tab==="handitems"){
const isHand=S.tab==="handitems", key=isHand?"pixelsquad_handitems":"pixelsquad_enables", title="Enables e Handitems", icon=isHand?"🎁":"✋", actionName=isHand?"handitem":"enable";
m.innerHTML='<div class="row"><h2>'+icon+' '+title+'</h2><input id="ps-enable-search" placeholder="Pesquisar por número ou nome..."></div><div class="filters"><button data-catalog-tab="enables" aria-pressed="'+!isHand+'">Enables</button><button data-catalog-tab="handitems" aria-pressed="'+isHand+'">Handitems</button><button id="ps-item-favorites" aria-pressed="false">☆ Favoritos</button></div><div class="enable-actions"><button id="ps-enable-refresh">Atualizar lista</button><span id="ps-enable-count" class="muted">0 itens</span></div><div class="enablegrid" id="ps-enable-list"></div>';
let onlyFavorites=false;
const list=()=>{
if(!m.isConnected||S.tab!==(isHand?"handitems":"enables"))return;
const search=m.querySelector("#ps-enable-search");if(!search)return;
const normalize=x=>String(x||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();const q=normalize(search.value);
const source=isHand?S.handitems:S.enables;
const arr=source.filter(x=>(!onlyFavorites||S.itemFavorites.includes(actionName+":"+x.id))&&(String(x.id).includes(q)||normalize(x.name).includes(q)));
m.querySelector("#ps-enable-count").textContent=arr.length+" itens";
m.querySelector("#ps-enable-list").innerHTML=arr.map(x=>{
return '<article class="enable-card"><div class="enable-number">ID '+esc(x.id)+'</div><button class="ps-item-star" data-item-favorite="'+esc(actionName+":"+x.id)+'" aria-label="Favoritar '+esc(x.name)+'" aria-pressed="'+S.itemFavorites.includes(actionName+":"+x.id)+'">'+(S.itemFavorites.includes(actionName+":"+x.id)?"★":"☆")+'</button><div class="ps-item-preview"><img loading="lazy" decoding="async" alt="'+esc(x.name)+'" src="'+esc(x.image)+'"><span hidden>Prévia indisponível</span></div><div class="enable-info"><strong>'+esc(x.name)+'</strong><b>ID #'+esc(x.id)+'</b><button data-item-action="'+actionName+'" data-item-id="'+esc(x.id)+'">Ativar</button></div></article>'
}).join("")||'<div class="status">Nenhum item encontrado.</div>';
for(const image of m.querySelectorAll(".ps-item-preview img")){
 image.onerror=()=>{image.hidden=true;image.parentElement.querySelector("span").hidden=false};
}
};
m.querySelector("#ps-enable-search").oninput=list;m.querySelector("#ps-item-favorites").onclick=e=>{onlyFavorites=!onlyFavorites;e.currentTarget.setAttribute("aria-pressed",String(onlyFavorites));list()};
m.querySelector("#ps-enable-refresh").onclick=async()=>{
const r=await chrome.storage.local.get([key]);
if(isHand)S.handitems=handitemsList(r[key]);else S.enables=enablesList(r[key]);
list();
};
m.onclick=e=>{
const tab=e.target.closest("[data-catalog-tab]");if(tab){S.tab=tab.dataset.catalogTab;persist();render();for(const nav of document.querySelectorAll("#ps-nav [data-tab]"))nav.classList.toggle("active",nav.dataset.tab===(S.tab==="handitems"?"enables":S.tab));return}
const star=e.target.closest("[data-item-favorite]");if(star){const key=star.dataset.itemFavorite;S.itemFavorites=S.itemFavorites.includes(key)?S.itemFavorites.filter(x=>x!==key):[...S.itemFavorites,key];persist();list();return}
const b=e.target.closest("[data-item-action]");
if(!b)return;
const id=b.dataset.itemId;
cmd(b.dataset.itemAction,id);
};
const initial=isHand?S.handitems:S.enables;
if(!initial.length)chrome.storage.local.get([key]).then(r=>{if(isHand)S.handitems=handitemsList(r[key]);else S.enables=enablesList(r[key]);list()});else list();
}
if(S.tab==="wired"){m.innerHTML='<h2>Wired / Super Wired</h2><input id="ps-wired-search" placeholder="Pesquisar..."><div class="filters"><button data-filter="" aria-pressed="true">Todos</button>'+["Ativadores","Efeitos","Condições","Seletores"].map(x=>'<button data-filter="'+x+'" aria-pressed="false">'+x+'</button>').join("")+'</div><div id="ps-wired-list"></div>';let f="";const list=()=>{const q=m.querySelector("#ps-wired-search").value.toLowerCase();m.querySelector("#ps-wired-list").innerHTML=wired.filter(x=>(!f||x[0]===f)&&x.join(" ").toLowerCase().includes(q)).map(x=>'<article class="card"><b>'+esc(x[0])+'</b><strong>'+esc(x[1])+'</strong><span>'+esc(x[2])+'</span><button data-wired="'+esc(x[1])+'">Gerar comando</button></article>').join("")};m.querySelector("#ps-wired-search").oninput=list;m.querySelector(".filters").onclick=e=>{const b=e.target.closest("[data-filter]");if(b){f=b.dataset.filter;for(const filter of m.querySelectorAll("[data-filter]"))filter.setAttribute("aria-pressed",String(filter.dataset.filter===f));list()}};m.onclick=e=>{const b=e.target.closest("[data-wired]");if(b){const p=prompt("Parâmetro do Super Wired (opcional):","");bridge(":"+b.dataset.wired+(p?":"+p:""))}};list()}
if(S.tab==="antiflood"){m.innerHTML="<h2>Anti-flood</h2>";window.PixelSquadAntiFlood?.settings(m)}
if(S.tab==="commands"){m.innerHTML='<h2>Comandos</h2><select id="ps-cmd">'+commands.map(x=>'<option>'+esc(x)+'</option>').join("")+'</select><input id="ps-param" placeholder="Parâmetro"><div class="out" id="ps-out"></div><div class="tools"><button id="ps-execute">Executar</button><button id="ps-copy">Copiar</button><button id="ps-save">Favoritar</button></div>';const update=()=>{const c=m.querySelector("#ps-cmd").value,p=m.querySelector("#ps-param").value.trim();m.querySelector("#ps-out").textContent=":"+c+(p?" "+p:"")};m.querySelector("#ps-cmd").onchange=update;m.querySelector("#ps-param").oninput=update;m.querySelector("#ps-execute").onclick=()=>bridge(m.querySelector("#ps-out").textContent);m.querySelector("#ps-copy").onclick=()=>navigator.clipboard?.writeText(m.querySelector("#ps-out").textContent);m.querySelector("#ps-save").onclick=()=>{const v=m.querySelector("#ps-out").textContent;if(!S.favorites.includes(v))S.favorites.push(v);persist();toast("Salvo")};update()}
if(S.tab==="chat"){m.innerHTML='<h2>Chat</h2><textarea id="ps-chat-text" rows="4" placeholder="Digite sua mensagem..."></textarea><div class="tools"><button id="ps-chat-send">Enviar</button><button id="ps-chat-copy">Copiar</button><button id="ps-chat-clear">Limpar</button></div><div class="status">Se a tradução estiver ligada, o texto enviado por este painel também será traduzido.</div>';m.querySelector("#ps-chat-send").onclick=()=>sendPanel(m.querySelector("#ps-chat-text").value);m.querySelector("#ps-chat-copy").onclick=()=>navigator.clipboard?.writeText(m.querySelector("#ps-chat-text").value);m.querySelector("#ps-chat-clear").onclick=()=>m.querySelector("#ps-chat-text").value=""}
if(S.tab==="translate"){const tr=window.PixelSquadTranslate,c=tr?.getConfig?.()||{},langs=tr?.langs||{};m.innerHTML='<h2>🌐 Tradução simultânea</h2><label><input id="tr-enabled" type="checkbox" '+(c.enabled?"checked":"")+'> Ativar</label><label>Idioma que eu escrevo<select id="tr-source">'+Object.entries(langs).map(([k,v])=>'<option value="'+k+'" '+(k===(c.source||"auto")?"selected":"")+'>'+esc(v)+'</option>').join("")+'</select></label><label>Idioma final<select id="tr-target">'+Object.entries(langs).filter(([k])=>k!=="auto").map(([k,v])=>'<option value="'+k+'" '+(k===(c.target||"pt")?"selected":"")+'>'+esc(v)+'</option>').join("")+'</select></label><label><input id="tr-out" type="checkbox" '+(c.outgoing!==false?"checked":"")+'> Traduzir o que eu envio</label><label><input id="tr-in" type="checkbox" '+(c.incoming!==false?"checked":"")+'> Traduzir o que recebo</label><label><input id="tr-original" type="checkbox" '+(c.showOriginal!==false?"checked":"")+'> Mostrar original abaixo</label><button id="tr-test">Testar agora</button><div class="out" id="tr-result">Pronto.</div><div class="status">Exemplo: escolha Português como idioma final. Se você escrever em inglês, espanhol, japonês etc., o PixelSquad traduz antes de enviar. Mensagens recebidas são traduzidas para o mesmo idioma.</div>';const save=()=>{const n={enabled:m.querySelector("#tr-enabled").checked,source:m.querySelector("#tr-source").value,target:m.querySelector("#tr-target").value,outgoing:m.querySelector("#tr-out").checked,incoming:m.querySelector("#tr-in").checked,showOriginal:m.querySelector("#tr-original").checked};tr.setConfig(n);if(n.enabled)tr.startObserver();else tr.stopObserver();toast(n.enabled?"Tradução ativada":"Tradução desativada")};["#tr-enabled","#tr-source","#tr-target","#tr-out","#tr-in","#tr-original"].forEach(s=>m.querySelector(s).onchange=save);m.querySelector("#tr-test").onclick=async()=>{const o=m.querySelector("#tr-result");o.textContent="Traduzindo...";try{const r=await tr.translate("Hello, how are you?",m.querySelector("#tr-target").value,m.querySelector("#tr-source").value);o.textContent=r.text+" • origem: "+(r.source||"auto")}catch(e){o.textContent="Erro: "+(e.message||e)}}}
if(S.tab==="tools"){m.innerHTML='<h2>Ferramentas</h2><div class="grid"><article><b>Anti-AFK</b><span>Comando nativo.</span><button data-tool="aus">Ativar</button></article><article><b>Velocidade</b><input id="ps-speed" placeholder="Número"><button data-tool="setspeed">Aplicar</button></article><article><b>Interação</b><input id="ps-tool-param" placeholder="Nick"><button data-tool="abracar">Abraçar</button><button data-tool="push">Empurrar</button><button data-tool="pull">Puxar</button></article><article><b>VIP</b><button data-tool="quickpoll">Enquete</button><button data-tool="tele">Teleporte</button></article></div>';m.onclick=e=>{const b=e.target.closest("[data-tool]");if(!b)return;const p=b.dataset.tool==="setspeed"?m.querySelector("#ps-speed").value.trim():m.querySelector("#ps-tool-param")?.value.trim()||"";cmd(b.dataset.tool,p)}}
if(S.tab==="settings"){m.innerHTML='<h2>Configurações</h2><label>Idioma do painel<select id="ps-language">'+Object.entries(PIXELSQUAD_LANGUAGES).map(([k,v])=>'<option value="'+k+'" '+(k===psGetLanguage()?"selected":"")+'>'+esc(v.name)+'</option>').join("")+'</select></label><section class="panel-position-settings"><b>Posição do painel</b><p class="muted">O painel abre por padrão na parte de baixo. Arraste o cabeçalho para qualquer ponto da tela e a posição ficará salva.</p><div class="tools"><button id="ps-reset-position">Restaurar posição padrão</button></div></section><div class="status">Preferências salvas no navegador. A tradução possui configuração independente na aba 🌐.</div><hr><small>PixelSquad • Pricilao.</small>';appearanceSettings(m);window.PixelSquadRGB?.settings(m);m.onclick=null;m.querySelector("#ps-language").onchange=e=>psSetLanguage(e.target.value);m.querySelector("#ps-reset-position").onclick=()=>{const box=document.querySelector("#pixelsquad .box");if(box){box.classList.remove("ps-custom-position");box.style.removeProperty("--ps-left");box.style.removeProperty("--ps-top")}localStorage.removeItem("pixelsquad_panel_position");toast("Posição padrão restaurada")}}}
window.addEventListener("message",e=>{if(e.source!==window||e.data?.source!=="pixelsquad")return;if(e.data.type==="PS_RESULT"){const r=e.data.result||{};toast(r.ok?"Habblet: "+(r.method||"ação")+" executado":"Habblet: "+(r.error||"falhou"))}if(e.data.type==="PS_DISCOVER_RESULT"){const r=e.data.result||{};toast(r.matches?.length?"Cliente detectado: "+r.matches.slice(0,4).map(x=>x.key).join(", "):"Nenhum módulo público detectado") }});
window.addEventListener("message",e=>{if(e.data?.source!=="pixelsquad"||e.data.type!=="PS_OPEN_PANEL")return;let allowed=e.source===window;if(!allowed){try{const u=new URL(e.origin);allowed=u.protocol==="https:"&&(u.hostname==="habblet.city"||u.hostname.endsWith(".habblet.city"))&&[...document.querySelectorAll("iframe")].some(f=>f.contentWindow===e.source)}catch{}}if(allowed)panel()});
window.addEventListener("pixelsquad-language-change",()=>{if(document.getElementById("pixelsquad"))panel()});
document.addEventListener("keydown",e=>{if(e.shiftKey&&e.key.toLowerCase()==="b"&&window.PixelSquadGame?.active===true){e.preventDefault();panel()}});
try{chrome.storage.local.get(["pixelsquad_enables","pixelsquad_handitems"]).then(r=>{S.enables=enablesList(r.pixelsquad_enables);S.handitems=handitemsList(r.pixelsquad_handitems)})}catch{}
try{chrome.runtime.onMessage.addListener(m=>{if(m?.type==="openPanel")panel()})}catch{}
const launch=document.createElement("button");launch.id="pixelsquad-launch";launch.type="button";launch.hidden=true;launch.title="PixelSquad";launch.setAttribute("aria-controls","pixelsquad");launch.setAttribute("aria-expanded","false");launch.setAttribute("aria-label","Abrir PixelSquad");const logo=document.createElement("img");logo.alt="PixelSquad";logo.src=chrome.runtime.getURL("icons/icon128.png");logo.onerror=()=>{logo.onerror=null;logo.src=chrome.runtime.getURL("icons/icon128.png")};launch.appendChild(logo);launch.onclick=togglePanel;document.documentElement.appendChild(launch);window.PixelSquadLauncher?.movable(launch);syncLauncher();window.addEventListener("pixelsquad-game-change",()=>{if(window.PixelSquadGame?.active!==true){closePanel();document.querySelector("#pixelsquad-avatar-generator [data-action=close]")?.click()}syncLauncher()});
})();