const PIXELSQUAD_LANGUAGES = {
  "pt-BR": { name: "Portugues (Brasil)", dir: "ltr", t: { home:"Inicio", build:"Construcao", wired:"Wired", effects:"Efeitos", commands:"Comandos", settings:"Configuracoes", language:"Idioma", languageTitle:"Idioma do PixelSquad", search:"Pesquisar", all:"Todos", save:"Salvar", copy:"Copiar", copied:"Copiado", close:"Fechar", creator:"Criador" } },
  "en": { name: "English", dir: "ltr", t: { home:"Home", build:"Build", wired:"Wired", effects:"Effects", commands:"Commands", settings:"Settings", language:"Language", languageTitle:"PixelSquad Language", search:"Search", all:"All", save:"Save", copy:"Copy", copied:"Copied", close:"Close", creator:"Creator" } },
  "es": { name: "Espanol", dir: "ltr", t: { home:"Inicio", build:"Construccion", wired:"Wired", effects:"Efectos", commands:"Comandos", settings:"Configuracion", language:"Idioma", languageTitle:"Idioma de PixelSquad", search:"Buscar", all:"Todos", save:"Guardar", copy:"Copiar", copied:"Copiado", close:"Cerrar", creator:"Creador" } },
  "fr": { name: "Francais", dir: "ltr", t: { home:"Accueil", build:"Construction", wired:"Wired", effects:"Effets", commands:"Commandes", settings:"Parametres", language:"Langue", languageTitle:"Langue de PixelSquad", search:"Rechercher", all:"Tous", save:"Enregistrer", copy:"Copier", copied:"Copie", close:"Fermer", creator:"Createur" } },
  "de": { name: "Deutsch", dir: "ltr", t: { home:"Start", build:"Bauen", wired:"Wired", effects:"Effekte", commands:"Befehle", settings:"Einstellungen", language:"Sprache", languageTitle:"PixelSquad Sprache", search:"Suchen", all:"Alle", save:"Speichern", copy:"Kopieren", copied:"Kopiert", close:"Schliessen", creator:"Ersteller" } },
  "it": { name: "Italiano", dir: "ltr", t: { home:"Home", build:"Costruzione", wired:"Wired", effects:"Effetti", commands:"Comandi", settings:"Impostazioni", language:"Lingua", languageTitle:"Lingua PixelSquad", search:"Cerca", all:"Tutti", save:"Salva", copy:"Copia", copied:"Copiato", close:"Chiudi", creator:"Creatore" } },
  "ru": { name: "Russian", dir: "ltr", t: { home:"Home", build:"Build", wired:"Wired", effects:"Effects", commands:"Commands", settings:"Settings", language:"Language", languageTitle:"PixelSquad Language", search:"Search", all:"All", save:"Save", copy:"Copy", copied:"Copied", close:"Close", creator:"Creator" } },
  "ja": { name: "Japanese", dir: "ltr", t: { home:"Home", build:"Build", wired:"Wired", effects:"Effects", commands:"Commands", settings:"Settings", language:"Language", languageTitle:"PixelSquad Language", search:"Search", all:"All", save:"Save", copy:"Copy", copied:"Copied", close:"Close", creator:"Creator" } },
  "ko": { name: "Korean", dir: "ltr", t: { home:"Home", build:"Build", wired:"Wired", effects:"Effects", commands:"Commands", settings:"Settings", language:"Language", languageTitle:"PixelSquad Language", search:"Search", all:"All", save:"Save", copy:"Copy", copied:"Copied", close:"Close", creator:"Creator" } },
  "zh-CN": { name: "Chinese", dir: "ltr", t: { home:"Home", build:"Build", wired:"Wired", effects:"Effects", commands:"Commands", settings:"Settings", language:"Language", languageTitle:"PixelSquad Language", search:"Search", all:"All", save:"Save", copy:"Copy", copied:"Copied", close:"Close", creator:"Creator" } },
  "ar": { name: "Arabic", dir: "rtl", t: { home:"Home", build:"Build", wired:"Wired", effects:"Effects", commands:"Commands", settings:"Settings", language:"Language", languageTitle:"PixelSquad Language", search:"Search", all:"All", save:"Save", copy:"Copy", copied:"Copied", close:"Close", creator:"Creator" } }
};
function psGetLanguage(){const s=localStorage.getItem("pixelsquad_language");return PIXELSQUAD_LANGUAGES[s]?s:"pt-BR"}
function psSetLanguage(s){if(PIXELSQUAD_LANGUAGES[s]){localStorage.setItem("pixelsquad_language",s);window.dispatchEvent(new CustomEvent("pixelsquad-language-change",{detail:s}))}}
function psT(k){const l=PIXELSQUAD_LANGUAGES[psGetLanguage()]||PIXELSQUAD_LANGUAGES["pt-BR"];return l.t[k]||PIXELSQUAD_LANGUAGES["pt-BR"].t[k]||k}
