const PIXELSQUAD_LANGUAGES = {
  "pt-BR": {name:"Português (Brasil)",dir:"ltr",t:{
    home:"Início",build:"Construção",wired:"Wired",effects:"Efeitos",commands:"Comandos",settings:"Configurações",
    language:"Idioma",creator:"Criador",search:"Pesquisar",all:"Todos",save:"Salvar",copy:"Copiar",copied:"Copiado",
    close:"Fechar",select:"Selecionar mobi",move:"Mover pilha",up:"Subir altura",down:"Descer altura",rotate:"Girar",
    freeze:"Congelar",unfreeze:"Descongelar",undo:"Desfazer",redo:"Refazer",teleport:"Teleporte",height:"Altura",
    direction:"Direção",parameter:"Parâmetro (opcional)",open:"Abrir painel no Habblet",noHabblet:"Abra o Habblet primeiro.",
    saved:"Salvo.",ready:"Pronto",applied:"Aplicado",notAvailable:"O controle correspondente não foi encontrado no cliente atual.",
    status:"Status",favorites:"Favoritos",languageSaved:"Idioma salvo automaticamente."
  }},
  "en": {name:"English",dir:"ltr",t:{
    home:"Home",build:"Build",wired:"Wired",effects:"Effects",commands:"Commands",settings:"Settings",
    language:"Language",creator:"Creator",search:"Search",all:"All",save:"Save",copy:"Copy",copied:"Copied",
    close:"Close",select:"Select furni",move:"Move stack",up:"Raise height",down:"Lower height",rotate:"Rotate",
    freeze:"Freeze",unfreeze:"Unfreeze",undo:"Undo",redo:"Redo",teleport:"Teleport",height:"Height",
    direction:"Direction",parameter:"Parameter (optional)",open:"Open panel in Habblet",noHabblet:"Open Habblet first.",
    saved:"Saved.",ready:"Ready",applied:"Applied",notAvailable:"The matching control was not found in the current client.",
    status:"Status",favorites:"Favorites",languageSaved:"Language is saved automatically."
  }},
  "es": {name:"Español",dir:"ltr",t:{home:"Inicio",build:"Construcción",wired:"Wired",effects:"Efectos",commands:"Comandos",settings:"Configuración",language:"Idioma",creator:"Creador",search:"Buscar",all:"Todos",save:"Guardar",copy:"Copiar",copied:"Copiado",close:"Cerrar",select:"Seleccionar furni",move:"Mover pila",up:"Subir altura",down:"Bajar altura",rotate:"Girar",freeze:"Congelar",unfreeze:"Descongelar",undo:"Deshacer",redo:"Rehacer",teleport:"Teletransporte",height:"Altura",direction:"Dirección",parameter:"Parámetro (opcional)",open:"Abrir panel en Habblet",noHabblet:"Abre Habblet primero.",saved:"Guardado.",ready:"Listo",applied:"Aplicado",notAvailable:"No se encontró el control correspondiente en el cliente actual.",status:"Estado",favorites:"Favoritos",languageSaved:"El idioma se guarda automáticamente."}},
  "fr": {name:"Français",dir:"ltr",t:{home:"Accueil",build:"Construction",wired:"Wired",effects:"Effets",commands:"Commandes",settings:"Paramètres",language:"Langue",creator:"Créateur",search:"Rechercher",all:"Tous",save:"Enregistrer",copy:"Copier",copied:"Copié",close:"Fermer",select:"Sélectionner un mobi",move:"Déplacer la pile",up:"Monter la hauteur",down:"Baisser la hauteur",rotate:"Tourner",freeze:"Geler",unfreeze:"Dégeler",undo:"Annuler",redo:"Rétablir",teleport:"Téléportation",height:"Hauteur",direction:"Direction",parameter:"Paramètre (facultatif)",open:"Ouvrir dans Habblet",noHabblet:"Ouvrez Habblet d'abord.",saved:"Enregistré.",ready:"Prêt",applied:"Appliqué",notAvailable:"Le contrôle correspondant est introuvable dans le client actuel.",status:"État",favorites:"Favoris",languageSaved:"La langue est enregistrée automatiquement."}},
  "de": {name:"Deutsch",dir:"ltr",t:{home:"Start",build:"Bauen",wired:"Wired",effects:"Effekte",commands:"Befehle",settings:"Einstellungen",language:"Sprache",creator:"Ersteller",search:"Suchen",all:"Alle",save:"Speichern",copy:"Kopieren",copied:"Kopiert",close:"Schließen",select:"Möbel auswählen",move:"Stapel bewegen",up:"Höhe erhöhen",down:"Höhe senken",rotate:"Drehen",freeze:"Einfrieren",unfreeze:"Auftauen",undo:"Rückgängig",redo:"Wiederholen",teleport:"Teleport",height:"Höhe",direction:"Richtung",parameter:"Parameter (optional)",open:"Panel in Habblet öffnen",noHabblet:"Öffne zuerst Habblet.",saved:"Gespeichert.",ready:"Bereit",applied:"Angewendet",notAvailable:"Die passende Steuerung wurde im aktuellen Client nicht gefunden.",status:"Status",favorites:"Favoriten",languageSaved:"Die Sprache wird automatisch gespeichert."}},
  "it": {name:"Italiano",dir:"ltr",t:{home:"Home",build:"Costruzione",wired:"Wired",effects:"Effetti",commands:"Comandi",settings:"Impostazioni",language:"Lingua",creator:"Creatore",search:"Cerca",all:"Tutti",save:"Salva",copy:"Copia",copied:"Copiato",close:"Chiudi",select:"Seleziona mobi",move:"Sposta pila",up:"Alza altezza",down:"Abbassa altezza",rotate:"Ruota",freeze:"Blocca",unfreeze:"Sblocca",undo:"Annulla",redo:"Ripristina",teleport:"Teletrasporto",height:"Altezza",direction:"Direzione",parameter:"Parametro (opzionale)",open:"Apri pannello in Habblet",noHabblet:"Apri prima Habblet.",saved:"Salvato.",ready:"Pronto",applied:"Applicato",notAvailable:"Il controllo corrispondente non è stato trovato nel client attuale.",status:"Stato",favorites:"Preferiti",languageSaved:"La lingua viene salvata automaticamente."}},
  "ru": {name:"Русский",dir:"ltr",t:{home:"Главная",build:"Строительство",wired:"Wired",effects:"Эффекты",commands:"Команды",settings:"Настройки",language:"Язык",creator:"Создатель",search:"Поиск",all:"Все",save:"Сохранить",copy:"Копировать",copied:"Скопировано",close:"Закрыть",select:"Выбрать мебель",move:"Переместить стопку",up:"Увеличить высоту",down:"Уменьшить высоту",rotate:"Повернуть",freeze:"Заморозить",unfreeze:"Разморозить",undo:"Отменить",redo:"Повторить",teleport:"Телепорт",height:"Высота",direction:"Направление",parameter:"Параметр (необязательно)",open:"Открыть в Habblet",noHabblet:"Сначала откройте Habblet.",saved:"Сохранено.",ready:"Готово",applied:"Применено",notAvailable:"Соответствующий элемент управления не найден в текущем клиенте.",status:"Статус",favorites:"Избранное",languageSaved:"Язык сохраняется автоматически."}},
  "ja": {name:"日本語",dir:"ltr",t:{home:"ホーム",build:"建築",wired:"Wired",effects:"効果",commands:"コマンド",settings:"設定",language:"言語",creator:"作成者",search:"検索",all:"すべて",save:"保存",copy:"コピー",copied:"コピーしました",close:"閉じる",select:"家具を選択",move:"スタックを移動",up:"高さを上げる",down:"高さを下げる",rotate:"回転",freeze:"固定",unfreeze:"固定解除",undo:"元に戻す",redo:"やり直す",teleport:"テレポート",height:"高さ",direction:"方向",parameter:"パラメータ（任意）",open:"Habbletで開く",noHabblet:"先にHabbletを開いてください。",saved:"保存しました。",ready:"準備完了",applied:"適用しました",notAvailable:"現在のクライアントに対応する操作が見つかりません。",status:"状態",favorites:"お気に入り",languageSaved:"言語は自動保存されます。"}},
  "ko": {name:"한국어",dir:"ltr",t:{home:"홈",build:"건설",wired:"Wired",effects:"효과",commands:"명령",settings:"설정",language:"언어",creator:"제작자",search:"검색",all:"전체",save:"저장",copy:"복사",copied:"복사됨",close:"닫기",select:"가구 선택",move:"스택 이동",up:"높이 올리기",down:"높이 내리기",rotate:"회전",freeze:"고정",unfreeze:"고정 해제",undo:"실행 취소",redo:"다시 실행",teleport:"텔레포트",height:"높이",direction:"방향",parameter:"매개변수(선택)",open:"Habblet에서 열기",noHabblet:"먼저 Habblet을 여세요.",saved:"저장됨.",ready:"준비 완료",applied:"적용됨",notAvailable:"현재 클라이언트에서 해당 컨트롤을 찾을 수 없습니다.",status:"상태",favorites:"즐겨찾기",languageSaved:"언어가 자동 저장됩니다."}},
  "zh-CN": {name:"简体中文",dir:"ltr",t:{home:"首页",build:"建造",wired:"Wired",effects:"效果",commands:"命令",settings:"设置",language:"语言",creator:"创建者",search:"搜索",all:"全部",save:"保存",copy:"复制",copied:"已复制",close:"关闭",select:"选择家具",move:"移动堆叠",up:"提高高度",down:"降低高度",rotate:"旋转",freeze:"冻结",unfreeze:"解冻",undo:"撤销",redo:"重做",teleport:"传送",height:"高度",direction:"方向",parameter:"参数（可选）",open:"在Habblet中打开",noHabblet:"请先打开Habblet。",saved:"已保存。",ready:"就绪",applied:"已应用",notAvailable:"当前客户端未找到对应控件。",status:"状态",favorites:"收藏",languageSaved:"语言会自动保存。"}},
  "ar": {name:"العربية",dir:"rtl",t:{home:"الرئيسية",build:"البناء",wired:"Wired",effects:"التأثيرات",commands:"الأوامر",settings:"الإعدادات",language:"اللغة",creator:"المنشئ",search:"بحث",all:"الكل",save:"حفظ",copy:"نسخ",copied:"تم النسخ",close:"إغلاق",select:"اختيار الأثاث",move:"تحريك المكدس",up:"رفع الارتفاع",down:"خفض الارتفاع",rotate:"تدوير",freeze:"تجميد",unfreeze:"إلغاء التجميد",undo:"تراجع",redo:"إعادة",teleport:"انتقال",height:"الارتفاع",direction:"الاتجاه",parameter:"المعامل (اختياري)",open:"فتح في Habblet",noHabblet:"افتح Habblet أولاً.",saved:"تم الحفظ.",ready:"جاهز",applied:"تم التطبيق",notAvailable:"لم يتم العثور على التحكم المطابق في العميل الحالي.",status:"الحالة",favorites:"المفضلة",languageSaved:"يتم حفظ اللغة تلقائياً."}}
};
for(const language of Object.values(PIXELSQUAD_LANGUAGES))language.t.antiflood="Anti-flood";
function psGetLanguage(){const s=localStorage.getItem("pixelsquad_language");return PIXELSQUAD_LANGUAGES[s]?s:"pt-BR"}
function psSetLanguage(s){if(PIXELSQUAD_LANGUAGES[s]){localStorage.setItem("pixelsquad_language",s);window.dispatchEvent(new CustomEvent("pixelsquad-language-change",{detail:s}))}}
function psT(k){const l=PIXELSQUAD_LANGUAGES[psGetLanguage()]||PIXELSQUAD_LANGUAGES["pt-BR"];return l.t[k]||PIXELSQUAD_LANGUAGES["pt-BR"].t[k]||k}

// PixelSquad CI update test
